artifacts:
  exported_at_utc: '2025-11-09T06:01:06'
  file_size_bytes: 5851168
  onnx_model: 20251109-1439.onnx
  opset_version: 12
  sequence_length: 180
data_info:
  feature_size: 274
  max_sequence_length: 180
  num_classes: 12
model_architecture:
  bidirectional: true
  embedding_dim: 512
  embedding_type: spatial
  encoder_type: masked_attention
  hidden_size: 256
  num_layers: 1
model_info:
  best_accuracy: 0.9878787878787879
  best_ckpt_iteration: 260
  best_f1_score: 0.9876413908671973
  best_loss: 0.05240995718067455
  total_steps: 260
  training_date: unknown
validation_metrics:
  accuracy: 0.9878787878787879
  f1_macro: 0.9876413908671974
  f1_weighted: 0.9876413908671973
  precision_weighted: 0.9886363636363636
  recall_weighted: 0.9878787878787879
  wer: 0.012121212121212088
  wer_scores:
    del_rate: 0.0
    ins_rate: 0.0
    sub_rate: 0.012121212121212088
vocab:
  classes:
  - 경주
  - 광명
  - 대구
  - 대전
  - 서울역
  - 수원
  - 아산
  - 영등포
  - 울산
  - 천안
  - 포항
  - <unk>
  num_classes: 12
